### ISSUE TITLE
ridiculous API that boasts over 9.6 billion possibilities

### ISSUE THREAD

**Issue by garmoshka-mo** [adorableio/avatars-api#35]
Here  http://avatars.adorable.io/ in FAQ said:

> we also offer access to a slightly more ridiculous API that boasts over 9.6 billion possibilities.

Where to get this api?

**Comment by rylnd** [comment]
Hey @garmoshka-mo! That's referring to our v2 api, which is a work in progress and thus not yet well-documented/-defined.

V2 allows you to build your own avatar specifying (for now) eyes, nose, mouth, and background color. Check out the relevant [routes](https://github.com/adorableio/avatars-api/blob/master/lib/routes/v2.coffee)  and [integration tests](https://github.com/adorableio/avatars-api/blob/master/test/integration.coffee#L39-L70) for more info, and please feel free to ask questions (or contribute!)

**Comment by itsthatguy** [comment]
a few examples:

`http://api.adorable.io/avatars/face/eyes1/nose4/mouth11/beb`
`http://api.adorable.io/avatars/face/eyes4/nose3/mouth4/eeb`

**Comment by rylnd** [comment]
@garmoshka-mo does that answer your question? We do need better documentation (see #28), but may I close this issue?

**Comment by garmoshka-mo** [comment]
Yeah, all's cool!
Maybe just add link on http://avatars.adorable.io/ in FAQ, so other users also not get confused

Thank you!
