### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by rylnd** [adorableio/avatars-api#36]
This was requested via email. Adding it to GitHub for visibility.

**Comment by itsthatguy** [comment]
+1

**Comment by bigtiger** [comment]
`I use SSL for my entire site, and I removed adorable avatars simply to get rid of "mixed content" errors.`

**Comment by zetas** [comment]
Can't you check out this repo and run your own version under ssl? The reason it doesn't work with the existing service is it's running from a heroku instance with a bad cert.

**Comment by zbuttram** [comment]
+1

**Comment by bigtiger** [comment]
<img width="573" alt="2016-02-18 at 9 09 pm" src="https://cloud.githubusercontent.com/assets/8511/13165532/13353810-d684-11e5-8ba4-6959aac6822d.png">

Support for SSL is now in place! Sorry for the delay.
