### ISSUE TITLE
Choose color

### ISSUE THREAD

**Issue by interaminense** [adorableio/avatars-api#39]
I can choose a color? how do I do?

**Comment by bigtiger** [comment]
There is but only if you choose each item:

/avatars/face/:eyes/:nose/:mouth/:color

Does this fit your needs or no?

**Comment by interaminense** [comment]
Bigtiger thanks for answering,

I do not know how to fill the color, example:

/avatars/face/eyes1/nose1/mouth1/:color

**Comment by bigtiger** [comment]
Ahh! It takes a hex code. Like [FFFFFF](http://www.color-hex.com/color/ffffff) (White) [000000](http://www.color-hex.com/color/000000) (Black) or [FF0000](http://www.color-hex.com/color/ff0000) Red

**Comment by interaminense** [comment]
That's it!! Thank you so much!

**Comment by bigtiger** [comment]
Aww Yiss!
