### ISSUE TITLE
Cache resultant avatars for future requests

### ISSUE THREAD

**Issue by bigtiger** [adorableio/avatars-api#51]
Request came from Twitter https://twitter.com/mgmarshalluk/status/752854367578054657

> Getting a delayed browser wait on the avatars, e.g. api.adorable.io/avatars/100/e8….  Can you cache them once generated? :)

**Comment by itsthatguy** [comment]
https://github.com/adorableio/avatars-api/tree/image_caching?files=1

**Comment by mgmarshall** [comment]
Hello, yes thanks for this.

Basically I am trying to use your avatars on my social site as currently we just have Gravatar, Facebook and Google. 

We use a UID for each user and their avatar shows like this:
https://api.adorable.io/avatars/100/e8f4a225e467d58270d48ed829615be4.png

When using it on the website, I am seeing up to a 7-8 second delay in it showing.  That is with only 1 avatar on screen.  If I put this live it would be dozens.

Here is the NET graph from Firebug, you can see its around 4 seconds here.

![adorable1](https://cloud.githubusercontent.com/assets/2814141/16769545/14e1cdd4-4841-11e6-942b-751ce32ef9c8.png)

Here is another one, on a page with lots of Gravatar requests (they are obviously blocking each other a bit)
![image](https://cloud.githubusercontent.com/assets/2814141/16769870/61e0664e-4842-11e6-8cb2-b48448885544.png)

Your service is completely free (and a breath of fresh air) so I understand why you would want to ignore this request.  But if there is anything you can do I would love to hear it :)

Thanks

Michael

**Comment by mgmarshall** [comment]
I just saw the post by **istthatguy** who shows a diff branch, thanks man.  I had no idea this was open source like this.  Do you have any plans to add caching to the branch running on http://avatars.adorable.io/ ?

**Comment by itsthatguy** [comment]
@mgmarshall yes, we do. As soon as we get time to wrap that work up, we will get it deployed, and close this issue.

**Comment by mgmarshall** [comment]
Thank you very much :D

**Comment by bigtiger** [comment]
Throwing more heroku dynos at this lately. We're going to need to spend some cycles on this coming up. I wonder whether the db is the best layer to cache this at. If not there, then where? If we had a persistent file store we could store them as static files. idk

**Comment by southpolesteve** [comment]
@bigtiger Not sure what it would cost at your bandwidth, but check out the heroku fastly add on. We're big fastly users (outside of heroku). A+ would recommend. Seems like a good solution for this problem.
