### ISSUE TITLE
Can you tell me about this ENDPOINT

### ISSUE THREAD

**Issue by udit-001** [adorableio/avatars-api#66]
How many possibilities are there, for this endpoint?

[http://api.adorable.io/avatar/](http://api.adorable.io/avatar/)

**Comment by bigtiger** [comment]
There are over 5000 avatars available at that endpoint.

**Comment by bigtiger** [comment]
10 eyes * 8 mouth * 8 nose * 9 colors = 5760

**Comment by rylnd** [comment]
@udit-001 see also https://github.com/adorableio/avatars-api/issues/35.

**Comment by udit-001** [comment]
@rylnd and @bigtiger perhaps you both misinterpreted my question.

I was talking about the endpoint which yields the following image as a result.

![Hi_mom](http://api.adorable.io/avatar/well)

**Comment by bigtiger** [comment]
That is a legacy endpoint. There are 11 unique responses. You could dig back through the repo to retrieve them if they were of interest to you.

**Comment by rylnd** [comment]
@udit-001 has your issue been addressed? If so, please close this.

**Comment by rylnd** [comment]
@udit-001 I'm closing this for now, please reopen or file a new issue as needed. I hope that we were able to help!
